### PR TITLE
Update Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by mirandapedro**
Translation worked was done mainly by João Vinícius de Andrade Santos (2016SANT66) and also by me.

### CODE REVIEW

**Comment by mirandapedro** [comment]
For future updates, I don't know how to prevent commits form previous PRs from my fork to carry over to new PRs? Does anyone know how I might fix this?

**Review by Ivan-Brigidano — APPROVED** [review]
LGTM

**Comment by Ivan-Brigidano** [comment]
> For future updates, I don't know how to prevent commits form previous PRs from my fork to carry over to new PRs? Does anyone know how I might fix this?

Maybe this will help you [Syncing a fork](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork).

**Comment by mirandapedro** [comment]
Thank you Iván for the reference!

**Pull request merged**
