### PR TITLE
Updated Vietnamese Regulations and Guidelines to Aug 1, 2020 version

### PR DESCRIPTION
**Pull request by Yoda8778**
I (2018DUON07) have retranslated the Vietnamese Regulations and in the process updating it to the 01-08-2020 version, as well as removing removed guidelines and adding new ones present in the 01-08-2020 version.

### CODE REVIEW

**Comment by mirandapedro** [comment]
Thank you very much for this. A new Regulations amendment is in an advanced stage an should go in to effect starting May 1st. 

Do you want us to publish this version of the translation and then work on the new one or would you rather wait and do it all in one go?

**Comment by Yoda8778** [comment]
I think I'd like for this version to be published first. I can revise this version later down the line.

**Comment by hanwu85** [comment]
Hi @Yoda8778 

Thank you very much for the update.

There are some checking errors in the system, could you find the reasons that cause the error?
Error from guidelines.md,  line 52 and line 174.
Error from regulations.md, line 237. 

Thanks!

**Comment by Yoda8778** [comment]
I think I've fixed the Travis issues. The build seems to be failing due to an issue with the pull command though.

**Comment by hanwu85** [comment]
Looks like we need an expert on this one.  @lgarron Any idea how to fix this error?

**Comment by gregorbg** [comment]
GitHub automatically closed this without my consent. Hang in there, working on a fix!

**Comment by gregorbg** [comment]
Because the PR is closed, I suddenly don't have write privileges to the fork anymore.
Had to create my own branch where I picked the original commits so that authorship is retained: https://github.com/thewca/wca-regulations-translations/pull/112

**Pull request closed without merging**
