### PR TITLE
update Chinese translation to ver. 2020-08-01

### PR DESCRIPTION
**Pull request by oyyq99999**

### CODE REVIEW

**Comment by hanwu85** [comment]
Hi Yunqi,

Thank you for the update.  
The travis check failed because the English version is not updated yet.  It is still the Jan 1st version.
Otherwise, this translation is okay, I will merge it around Aug 1st, is that okay to you?

**Comment by oyyq99999** [comment]
Sure. Same occasion as last time.

**Comment by oyyq99999** [comment]
Added some old changes accidentally noticed.

**Comment by lgarron** [comment]
@Baiqiang, could I ask you to do a second check of this PR to before we merge?

**Comment by oyyq99999** [comment]
fixed an inconsistent link as thewca/regulations#982

**Comment by oyyq99999** [comment]
Seems the WCA website should update the translation versions since two weeks have past.

**Comment by hanwu85** [comment]
@oyyq99999 thank you for the reminder!  We will update the page.

**Pull request merged**
