### PR TITLE
2016 update - Portuguese European

### PR DESCRIPTION
**Pull request by cubizh**
Updated 2016 translation for the portuguese european.

### CODE REVIEW

**Comment by Claster** [comment]
Hi,

There are several small problems with the translation:
1) There is no A3d1 and D1c anymore, you should delete them;
2) 7f1a in Guidelines has no "+" sign;
3) We deprecated "SEPARATE" label. Could you please remove "SEPARADO" from everywhere?
4) A5b+ and C1b+++ are missing in your translation, however there should be no C1b2+ (most likely C1b2+ should be just C1b+++).

**Comment by lgarron** [comment]
@cubizh: Would you be able to fix the issues pointed out by @Claster 

Also tagging @viroulep for formatting knowledge.

**Comment by cubizh** [comment]
Given the mistakes that were encountered I decided to do a complete one from scratch, not ready yet.

**Comment by Laura-O** [comment]
Closing this one as there hasn't been an update since ~3 months.

**Pull request closed without merging**
