### PR TITLE
Update Japanese translation to version 2019-05-01

### PR DESCRIPTION
**Pull request by kotarot**
Hi,
We've completed the Japanese translation of Regulations and Guidelines to the latest version. Our Delegate [Yuki Tanaka](https://www.worldcubeassociation.org/persons/2010TANA02) (@yktanaka) has checked and confirmed the content. Would someone please merge this and update the WCA website?

### CODE REVIEW

**Comment by kotarot** [comment]
Sorry, can you wait for just a second please? We need a few more fixes.

**Comment by kotarot** [comment]
Fixed and everything is alright!

**Comment by kotarot** [comment]
@viroulep @lgarron Hi, could you please check this if you have time?

**Comment by lgarron** [comment]
@yktanaka verified the update via email!

**Comment by kotarot** [comment]
Thanks, Lucas and Yuki!

**Pull request merged**
