### PR TITLE
Added Swedish translations

### PR DESCRIPTION
**Pull request by viktorzenk**
I have translated and proofread the Regulations and Guidelines into Swedish.

### CODE REVIEW

**Review by Ivan-Brigidano — APPROVED** [review]

**Comment by viktorzenk** [comment]
I saw that the commit was merged to main, thanks!
Is there an estimate as to when the translated regulations will be visible on the website?

**Comment by Ivan-Brigidano** [comment]
The translation should be available as soon as the WST merges [this PR](https://github.com/thewca/worldcubeassociation.org/pull/6417). Most likely in a few days.

**Comment by viktorzenk** [comment]
Great, thanks!

**Comment by gregorbg** [comment]
Fun fact: Due to Swedish not being included in the regulations compiler until now (see https://github.com/thewca/wca-regulations-compiler/commit/cfe027e9e67d7ce69ccf28c062e16ec203887fd9) this PR was never properly checked.

The check mechanism went through because all other languages that are routinely checked are just fine (because obviously they were never touched in this PR). Swedish was never checked on top of that. There are a few minor formatting changes which I will fix directly, hang in there!

**Comment by gregorbg** [comment]
This is now live at https://www.worldcubeassociation.org/regulations/translations/swedish/ :partying_face: Thank you for your efforts in translating the regulations document, Viktor!

**Comment by viktorzenk** [comment]
Thank you!

I noticed a small formatting error in the numbering disclaimer under the
section "Contents" ("Innehåll").
The hyphen in the Swedish sentence "OBS: Eftersom Artikel- och Regelnummer
inte omfördelas när Regler raderas kan det finnas luckor i numreringen." is
interpreted as a bullet point.
The sentence is displayed correctly in the MD file preview at
https://github.com/thewca/wca-regulations-translations/blob/main/swedish/wca-regulations.md
.

I'm not sure how to fix this, maybe you have an idea?
If it can't easily be fixed, the sentence could be rewritten without the
hyphen notation as:
"OBS: Eftersom numreringen för Artiklar och Regler inte omfördelas när
Regler raderas kan det finnas luckor i numreringen."

Thank you for your work!
Viktor

**Pull request merged**
