### PR TITLE
Updated Tradition Chinese to 2019-05-01 Ver!

### PR DESCRIPTION
**Pull request by hanwu85**
Finally completed.
Both Regulations and Guidelines are finished.
Shout out to Chia-Leo Lin (林珈樂) @richar983, thanks for the double checking.

### CODE REVIEW

**Comment by hanwu85** [comment]
Error fixed! Thanks, Lucas!

**Comment by lgarron** [comment]
Thanks!

**Comment by hanwu85** [comment]
The website is still showing the old version, is there anything that need to be changed in order to show the new branch?

**Comment by kotarot** [comment]
Hi, Han. I just commented here at almost the same time 😆 😆 😆 I suppose the software team needs to build the regulations to update to the latest
https://github.com/thewca/worldcubeassociation.org/pull/4625#issuecomment-533784065

**Comment by jonatanklosko** [comment]
I've just rebuilt regulations, should be good now =)

**Comment by hanwu85** [comment]
Thank you all!!

**Pull request merged**
