### PR TITLE
update Chinese translation to ver. 2023-02-01

### PR DESCRIPTION
**Pull request by oyyq99999**

### CODE REVIEW

**Comment by hanwu85** [comment]
Thank you for the translation as always.
Apart from the inconsistent of "Stackmat计时器" and "计时器", it seems good to me.
@oyyq99999, if you are fine with it, I will approve it.

**Comment by oyyq99999** [comment]
@hanwu85 The changes are based on official changes. Is there any inconsistency with the official version? If not, that's fine.

**Comment by hanwu85** [comment]
@oyyq99999 
It's just the name of the timer, I think it is fine. I am going to approve it.
Thank you very much.

**Review by hanwu85 — APPROVED** [review]
LGTM.

**Pull request merged**
