### PR TITLE
Update Russian translation of Regulations and Guidlines to version 2022-01-01

### PR DESCRIPTION
**Pull request by TimWCA**
Regulations and Guidlines updated to ver. 2022-01-01, mistakes fixed

### CODE REVIEW

**Comment by AlexKatyukov** [comment]
Hi!
We (@TimWCA, @Niksson, @Nevseros and me) make a big work to find all mistakes and controversial language issues.
Ready for questions if needed (:

**Comment by Niksson** [comment]
@Ivan-Brigidano, any updates on the review?

**Review by Ivan-Brigidano — APPROVED** [review]

**Comment by Ivan-Brigidano** [comment]
> @Ivan-Brigidano, any updates on the review?

This PR is ready to be merged, right?

**Comment by TimWCA** [comment]
> > @Ivan-Brigidano, any updates on the review?
> 
> This PR is ready to be merged, right?

Yes

**Comment by AlexKatyukov** [comment]
When can we see this on WCA website? :)

**Comment by Nevseros** [comment]
> When can we see this on WCA website? :)

Probably after thewca/worldcubeassociation.org#6622 will be merged.

**Comment by mirandapedro** [comment]
Hi, this is now live at https://www.worldcubeassociation.org/regulations/translations/russian/

Thanks to everyone who contributed!

**Pull request merged**
