### PR TITLE
Update Japanese translation version 2020-01-01

### PR DESCRIPTION
**Pull request by kotarot**
Hi WRC,

We have updated Japanese translation to the latest!
WCA Delegates Shuhei (@shuhei444), Yuki (@yktanaka), and also Han (@hanwu85) checked and verified the contents (https://github.com/kotarot/wca-regulations-translations/pull/63).
Please merge it if it seems to be OK. Thanks.

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks! I like the idea of having a glosary!

**Comment by kotarot** [comment]
Thanks Lucas!

**Comment by kotarot** [comment]
> I like the idea of having a glosary!

That is Han's idea! He has created one in Traditional Chinese.

**Comment by hanwu85** [comment]
Yeah, I think it is good idea to make a glossary for vocabulary coherence, and if someone else is taking over the translation, it will still stay the same.  @kotarot made it better by adding writing style guide. 💯

**Pull request merged**
