### PR TITLE
update chinese translation to ver. 2017-06-19

### PR DESCRIPTION
**Pull request by cs0x7f**
Well, it seems that most of the updates of the regulation or guideline are typos. Hence, there is only a few updates in Chinese translation compared to previous version.

### CODE REVIEW

**Comment by lgarron** [comment]
@cs0x7f I'm sorry, this seems to have been unaddressed. Is it still good to merge?

**Comment by cs0x7f** [comment]
Yes, of course. It's translated according to the official branch. It seems that the official branch has not been changed in the past 3 months.

**Comment by lgarron** [comment]
Thanks for the confirmation! I'll merge and push it right now.

**Comment by lgarron** [comment]
Updated!

Please check that the HTML and PDF look good. :-)
https://www.worldcubeassociation.org/regulations/translations/chinese/

**Pull request merged**
